In [14]:
import torch
import torch.nn as nn

max_seq = 10
d_model = 6

In [3]:
even_i = torch.arange(0,d_model,2).float()
even_i

tensor([0., 2., 4.])

In [6]:
eve_de = torch.pow(10000,even_i/d_model)
eve_de

tensor([  1.0000,  21.5443, 464.1590])

In [8]:
odd_i = torch.arange(0,d_model,2).float()
odd_i

tensor([0., 2., 4.])

In [12]:
eve_de = torch.pow(10000,(odd_i-1)/d_model)
eve_de

tensor([  0.2154,   4.6416, 100.0000])

In [16]:
position = torch.arange(max_seq,dtype=torch.float).reshape(max_seq,1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [17]:
de = eve_de

In [18]:
even_pe = torch.sin(position/de)
odd_pe = torch.cos(position/de)

In [19]:
even_pe

tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.9975,  0.2138,  0.0100],
        [ 0.1411,  0.4177,  0.0200],
        [ 0.9775,  0.6023,  0.0300],
        [-0.2794,  0.7590,  0.0400],
        [-0.9380,  0.8806,  0.0500],
        [ 0.4121,  0.9616,  0.0600],
        [ 0.8797,  0.9980,  0.0699],
        [-0.5366,  0.9884,  0.0799],
        [-0.8038,  0.9330,  0.0899]])

In [22]:
stacked = torch.stack([even_pe,odd_pe],dim=2)

In [24]:
stacked.shape

torch.Size([10, 3, 2])

In [25]:
PE = torch.flatten(stacked,start_dim=1,end_dim=2)

In [26]:
PE

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [-0.9975, -0.0707,  0.2138,  0.9769,  0.0100,  0.9999],
        [ 0.1411, -0.9900,  0.4177,  0.9086,  0.0200,  0.9998],
        [ 0.9775,  0.2108,  0.6023,  0.7983,  0.0300,  0.9996],
        [-0.2794,  0.9602,  0.7590,  0.6511,  0.0400,  0.9992],
        [-0.9380, -0.3467,  0.8806,  0.4738,  0.0500,  0.9988],
        [ 0.4121, -0.9111,  0.9616,  0.2746,  0.0600,  0.9982],
        [ 0.8797,  0.4756,  0.9980,  0.0627,  0.0699,  0.9976],
        [-0.5366,  0.8438,  0.9884, -0.1522,  0.0799,  0.9968],
        [-0.8038, -0.5949,  0.9330, -0.3599,  0.0899,  0.9960]])

Class

In [27]:
import torch
import torch.nn as nn

class PositionalEncoding(nn.Module):

    def __init__(self, d_model, max_sequence_length):
        super().__init__()
        self.max_sequence_length = max_sequence_length
        self.d_model = d_model

    def forward(self):
        even_i = torch.arange(0, self.d_model, 2).float()
        denominator = torch.pow(10000, even_i/self.d_model)
        position = torch.arange(self.max_sequence_length).reshape(self.max_sequence_length, 1)
        even_PE = torch.sin(position / denominator)
        odd_PE = torch.cos(position / denominator)
        stacked = torch.stack([even_PE, odd_PE], dim=2)
        PE = torch.flatten(stacked, start_dim=1, end_dim=2)
        return PE

In [28]:
pe = PositionalEncoding(d_model=6, max_sequence_length=10)
pe.forward()

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999],
        [ 0.9894, -0.1455,  0.3629,  0.9318,  0.0172,  0.9999],
        [ 0.4121, -0.9111,  0.4057,  0.9140,  0.0194,  0.9998]])